"""Added the vendorID to the OrderProduct Table

Revision ID: 9ddde38b96d0
Revises: fd376ffac86e
Create Date: 2022-08-13 12:11:24.934586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddde38b96d0'
down_revision = 'fd376ffac86e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_products', 'vendors', ['vendor_id'], ['id'])
    op.drop_constraint('placed_orders_vendor_id_fkey', 'placed_orders', type_='foreignkey')
    op.drop_column('placed_orders', 'vendor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placed_orders', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('placed_orders_vendor_id_fkey', 'placed_orders', 'vendors', ['vendor_id'], ['id'])
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.drop_column('order_products', 'vendor_id')
    # ### end Alembic commands ###
